name: Sync Fork

on:
  schedule:
    - cron: '*/1 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: mollyim/mollyim-android@v1.6
        with:
          base: master
          head: master
